//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.18444
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Eagle.WebApp.App_GlobalResources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class SiteMapLocalizations {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal SiteMapLocalizations() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Eagle.WebApp.App_GlobalResources.SiteMapLocalizations", typeof(SiteMapLocalizations).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to A01a-TS.
        /// </summary>
        public static string A01aTS {
            get {
                return ResourceManager.GetString("A01aTS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to A01-TS.
        /// </summary>
        public static string A01TS {
            get {
                return ResourceManager.GetString("A01TS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Phân quyền người dùng.
        /// </summary>
        public static string Access {
            get {
                return ResourceManager.GetString("Access", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tài khoản.
        /// </summary>
        public static string Account {
            get {
                return ResourceManager.GetString("Account", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Quản lý thông tin người dùng.
        /// </summary>
        public static string AccountManagement {
            get {
                return ResourceManager.GetString("AccountManagement", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Thêm form chức năng.
        /// </summary>
        public static string AddForm {
            get {
                return ResourceManager.GetString("AddForm", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Thêm thông tin danh mục.
        /// </summary>
        public static string AddMenu {
            get {
                return ResourceManager.GetString("AddMenu", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Thêm mới.
        /// </summary>
        public static string AddNew {
            get {
                return ResourceManager.GetString("AddNew", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Thêm ứng viên.
        /// </summary>
        public static string AddNewCandidate {
            get {
                return ResourceManager.GetString("AddNewCandidate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Thêm nhân viên.
        /// </summary>
        public static string AddNewEmployee {
            get {
                return ResourceManager.GetString("AddNewEmployee", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Gán nhân viên vào lịch.
        /// </summary>
        public static string AssignStaffSchedule {
            get {
                return ResourceManager.GetString("AssignStaffSchedule", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Dữ liệu nền.
        /// </summary>
        public static string BackgroundData {
            get {
                return ResourceManager.GetString("BackgroundData", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cấu hình cơ bản.
        /// </summary>
        public static string BasicConfiguration {
            get {
                return ResourceManager.GetString("BasicConfiguration", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Quản lý nhãn hiệu.
        /// </summary>
        public static string BrandManagement {
            get {
                return ResourceManager.GetString("BrandManagement", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to C66a-HD.
        /// </summary>
        public static string C66a {
            get {
                return ResourceManager.GetString("C66a", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to C67a-HD.
        /// </summary>
        public static string C67a {
            get {
                return ResourceManager.GetString("C67a", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to C68a-HD.
        /// </summary>
        public static string C68a {
            get {
                return ResourceManager.GetString("C68a", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to C69a-HD.
        /// </summary>
        public static string C69a {
            get {
                return ResourceManager.GetString("C69a", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to C70a-HD.
        /// </summary>
        public static string C70a {
            get {
                return ResourceManager.GetString("C70a", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Báo cáo chuyên sâu tài chính.
        /// </summary>
        public static string CAFR {
            get {
                return ResourceManager.GetString("CAFR", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Báo cáo đánh giá ứng viên.
        /// </summary>
        public static string CandidateEvaluationReport {
            get {
                return ResourceManager.GetString("CandidateEvaluationReport", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Lý lịch ứng viên.
        /// </summary>
        public static string CandidateInformation {
            get {
                return ResourceManager.GetString("CandidateInformation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Danh sách ứng viên.
        /// </summary>
        public static string CandidateList {
            get {
                return ResourceManager.GetString("CandidateList", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Quản lý ngành hàng.
        /// </summary>
        public static string CategoryManagement {
            get {
                return ResourceManager.GetString("CategoryManagement", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Đổi mật khẩu.
        /// </summary>
        public static string ChangePassword {
            get {
                return ResourceManager.GetString("ChangePassword", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Công ty.
        /// </summary>
        public static string Company {
            get {
                return ResourceManager.GetString("Company", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Thông tin công ty.
        /// </summary>
        public static string CompanyInfomation {
            get {
                return ResourceManager.GetString("CompanyInfomation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Hợp đồng lao động.
        /// </summary>
        public static string Contract {
            get {
                return ResourceManager.GetString("Contract", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Quản lý hợp đồng.
        /// </summary>
        public static string ContractManagement {
            get {
                return ResourceManager.GetString("ContractManagement", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Nghỉ dưỡng sức.
        /// </summary>
        public static string Convalescence {
            get {
                return ResourceManager.GetString("Convalescence", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Thêm.
        /// </summary>
        public static string Create {
            get {
                return ResourceManager.GetString("Create", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Thêm nhân viên.
        /// </summary>
        public static string CreateEmployee {
            get {
                return ResourceManager.GetString("CreateEmployee", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to D02-TS.
        /// </summary>
        public static string D02TS {
            get {
                return ResourceManager.GetString("D02TS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to D07-TS.
        /// </summary>
        public static string D07TS {
            get {
                return ResourceManager.GetString("D07TS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Phân quyền dữ liệu.
        /// </summary>
        public static string DataPermission {
            get {
                return ResourceManager.GetString("DataPermission", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ủy quyền.
        /// </summary>
        public static string Delegate {
            get {
                return ResourceManager.GetString("Delegate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Phòng ban.
        /// </summary>
        public static string Department {
            get {
                return ResourceManager.GetString("Department", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Quản lý nhà phân phối.
        /// </summary>
        public static string DistributorManagement {
            get {
                return ResourceManager.GetString("DistributorManagement", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sửa thông tin nhân viên.
        /// </summary>
        public static string EditEmployee {
            get {
                return ResourceManager.GetString("EditEmployee", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Chỉnh sửa tiểu sử.
        /// </summary>
        public static string EditProfile {
            get {
                return ResourceManager.GetString("EditProfile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Xử lý thôi việc.
        /// </summary>
        public static string EditTermination {
            get {
                return ResourceManager.GetString("EditTermination", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Nhân sự.
        /// </summary>
        public static string Employee {
            get {
                return ResourceManager.GetString("Employee", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Danh sách nhân viên.
        /// </summary>
        public static string EmployeeList {
            get {
                return ResourceManager.GetString("EmployeeList", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Quản lý nhân viên.
        /// </summary>
        public static string EmployeeManagement {
            get {
                return ResourceManager.GetString("EmployeeManagement", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Lý lịch nhân viên.
        /// </summary>
        public static string EmployeeProfile {
            get {
                return ResourceManager.GetString("EmployeeProfile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Quan hệ gia đình.
        /// </summary>
        public static string FamilyRelationship {
            get {
                return ResourceManager.GetString("FamilyRelationship", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Quản lý form chức năng.
        /// </summary>
        public static string FormManagement {
            get {
                return ResourceManager.GetString("FormManagement", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Nghỉ bảo hiểm.
        /// </summary>
        public static string FunctionName_LeaveInsurance {
            get {
                return ResourceManager.GetString("FunctionName_LeaveInsurance", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Phân quyền chức năng.
        /// </summary>
        public static string FunctionPermission {
            get {
                return ResourceManager.GetString("FunctionPermission", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Thông tin chung.
        /// </summary>
        public static string GeneralInformation {
            get {
                return ResourceManager.GetString("GeneralInformation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Quản lý nhóm.
        /// </summary>
        public static string GroupManagement {
            get {
                return ResourceManager.GetString("GroupManagement", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ngày nghỉ / lễ.
        /// </summary>
        public static string Holidays {
            get {
                return ResourceManager.GetString("Holidays", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Bảng điều khiển.
        /// </summary>
        public static string Home {
            get {
                return ResourceManager.GetString("Home", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Bệnh viện.
        /// </summary>
        public static string Hospital {
            get {
                return ResourceManager.GetString("Hospital", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Báo cáo nhân sự.
        /// </summary>
        public static string HRReport {
            get {
                return ResourceManager.GetString("HRReport", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Chi tiết làm thêm của nhân viên.
        /// </summary>
        public static string IndividualOT {
            get {
                return ResourceManager.GetString("IndividualOT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Dữ liệu báo bảo hiểm.
        /// </summary>
        public static string InsNoticeData {
            get {
                return ResourceManager.GetString("InsNoticeData", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Bảo hiểm.
        /// </summary>
        public static string Insurance {
            get {
                return ResourceManager.GetString("Insurance", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Phỏng vấn.
        /// </summary>
        public static string Interview {
            get {
                return ResourceManager.GetString("Interview", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Lịch phỏng vấn.
        /// </summary>
        public static string InterviewCalendar {
            get {
                return ResourceManager.GetString("InterviewCalendar", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tiêu chí phỏng vấn.
        /// </summary>
        public static string InterviewCriteria {
            get {
                return ResourceManager.GetString("InterviewCriteria", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Loại tiêu chí phỏng vấn.
        /// </summary>
        public static string InterviewCriteriaType {
            get {
                return ResourceManager.GetString("InterviewCriteriaType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Báo cáo đánh giá kết quả phỏng vấn.
        /// </summary>
        public static string InterviewEvaluationReport {
            get {
                return ResourceManager.GetString("InterviewEvaluationReport", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Đặt lịch phỏng vấn.
        /// </summary>
        public static string InterviewSchedule {
            get {
                return ResourceManager.GetString("InterviewSchedule", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Dự án tham gia.
        /// </summary>
        public static string JoinedProjects {
            get {
                return ResourceManager.GetString("JoinedProjects", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Hợp đồng lao động.
        /// </summary>
        public static string LaborContracts {
            get {
                return ResourceManager.GetString("LaborContracts", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Đơn xin nghỉ phép.
        /// </summary>
        public static string LeaveApplication {
            get {
                return ResourceManager.GetString("LeaveApplication", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Chi tiết loại nghỉ.
        /// </summary>
        public static string LeaveDayType {
            get {
                return ResourceManager.GetString("LeaveDayType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Nghỉ bảo hiểm.
        /// </summary>
        public static string LeaveOfInsurance {
            get {
                return ResourceManager.GetString("LeaveOfInsurance", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Quản lý nghỉ phép.
        /// </summary>
        public static string LeaveRecord {
            get {
                return ResourceManager.GetString("LeaveRecord", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Danh mục loại nghỉ.
        /// </summary>
        public static string LeaveType {
            get {
                return ResourceManager.GetString("LeaveType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Danh sách tham gia BH.
        /// </summary>
        public static string ListOfParticipating {
            get {
                return ResourceManager.GetString("ListOfParticipating", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Thông tin dữ liệu nền.
        /// </summary>
        public static string MasterDataInfo {
            get {
                return ResourceManager.GetString("MasterDataInfo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Qui trình online.
        /// </summary>
        public static string MasterDataOnlineProcess {
            get {
                return ResourceManager.GetString("MasterDataOnlineProcess", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Quản lý danh mục chức năng.
        /// </summary>
        public static string MenuManagement {
            get {
                return ResourceManager.GetString("MenuManagement", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tổng hợp làm ngoài giờ theo tháng.
        /// </summary>
        public static string MonthlyOTReport {
            get {
                return ResourceManager.GetString("MonthlyOTReport", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Chi tiết chấm công.
        /// </summary>
        public static string MonthlyTimeKeepingReport {
            get {
                return ResourceManager.GetString("MonthlyTimeKeepingReport", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Danh sách nhân viên nuôi con nhỏ &lt; 12 tháng.
        /// </summary>
        public static string MTLChild {
            get {
                return ResourceManager.GetString("MTLChild", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tổng số tháng.
        /// </summary>
        public static string NoOfMonth {
            get {
                return ResourceManager.GetString("NoOfMonth", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Qui trình online - chi tiết.
        /// </summary>
        public static string OnlineProcessDetail {
            get {
                return ResourceManager.GetString("OnlineProcessDetail", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Qui trình online.
        /// </summary>
        public static string OnlineProcessMaster {
            get {
                return ResourceManager.GetString("OnlineProcessMaster", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Giới hạn làm ngoài giờ.
        /// </summary>
        public static string OTLimitByStaff {
            get {
                return ResourceManager.GetString("OTLimitByStaff", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Danh sách nhân viên làm ca đêm.
        /// </summary>
        public static string OTNightRecord {
            get {
                return ResourceManager.GetString("OTNightRecord", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Danh sách nhân viên làm thêm giờ.
        /// </summary>
        public static string OTRecord {
            get {
                return ResourceManager.GetString("OTRecord", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Đơn làm thêm ngoài giờ.
        /// </summary>
        public static string OTRequest {
            get {
                return ResourceManager.GetString("OTRequest", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Danh sách đơn làm thêm ngoài giờ.
        /// </summary>
        public static string OTRequestRecord {
            get {
                return ResourceManager.GetString("OTRequestRecord", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Lương.
        /// </summary>
        public static string Payroll {
            get {
                return ResourceManager.GetString("Payroll", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tham số lương, bảo hiểm.
        /// </summary>
        public static string PayrollInsuranceParameter {
            get {
                return ResourceManager.GetString("PayrollInsuranceParameter", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Nhân sự.
        /// </summary>
        public static string Personnel {
            get {
                return ResourceManager.GetString("Personnel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Báo cáo nhân sự.
        /// </summary>
        public static string PersonnelReport {
            get {
                return ResourceManager.GetString("PersonnelReport", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Danh sách kế hoạch tuyển dụng.
        /// </summary>
        public static string PlanList {
            get {
                return ResourceManager.GetString("PlanList", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Quy trình tuyển Dụng.
        /// </summary>
        public static string ProcessRecruitment {
            get {
                return ResourceManager.GetString("ProcessRecruitment", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Quản lý sản phẩm.
        /// </summary>
        public static string ProductManagement {
            get {
                return ResourceManager.GetString("ProductManagement", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tiểu sử.
        /// </summary>
        public static string Profile {
            get {
                return ResourceManager.GetString("Profile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tiểu sử.
        /// </summary>
        public static string ProfileManagement {
            get {
                return ResourceManager.GetString("ProfileManagement", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Dự án.
        /// </summary>
        public static string Project {
            get {
                return ResourceManager.GetString("Project", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Quản lý dự án.
        /// </summary>
        public static string ProjectManagement {
            get {
                return ResourceManager.GetString("ProjectManagement", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Bằng cấp - Chứng chỉ.
        /// </summary>
        public static string Qualification {
            get {
                return ResourceManager.GetString("Qualification", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Quản lý bằng cấp.
        /// </summary>
        public static string QualificationManagement {
            get {
                return ResourceManager.GetString("QualificationManagement", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Định biên tuyển dụng.
        /// </summary>
        public static string QuotaRecruitment {
            get {
                return ResourceManager.GetString("QuotaRecruitment", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Chuyển phép năm.
        /// </summary>
        public static string Reconciliation {
            get {
                return ResourceManager.GetString("Reconciliation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tuyển Dụng.
        /// </summary>
        public static string Recruitment {
            get {
                return ResourceManager.GetString("Recruitment", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Yêu cầu tuyển dụng.
        /// </summary>
        public static string RecruitmentDemand {
            get {
                return ResourceManager.GetString("RecruitmentDemand", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Danh sách yêu cầu tuyển dụng.
        /// </summary>
        public static string RecruitmentDemandRecord {
            get {
                return ResourceManager.GetString("RecruitmentDemandRecord", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Chi phí tuyển dụng.
        /// </summary>
        public static string RecruitmentFee {
            get {
                return ResourceManager.GetString("RecruitmentFee", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Kế hoạc tuyển dụng.
        /// </summary>
        public static string RecruitmentPlan {
            get {
                return ResourceManager.GetString("RecruitmentPlan", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Phương án tuyển dụng.
        /// </summary>
        public static string RecruitmentProject {
            get {
                return ResourceManager.GetString("RecruitmentProject", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Danh sách phương án tuyển dụng.
        /// </summary>
        public static string RecruitmentProjectList {
            get {
                return ResourceManager.GetString("RecruitmentProjectList", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Nguồn tuyển dụng.
        /// </summary>
        public static string RecruitmentSource {
            get {
                return ResourceManager.GetString("RecruitmentSource", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Vòng tuyển dụng.
        /// </summary>
        public static string RecruitmentTournament {
            get {
                return ResourceManager.GetString("RecruitmentTournament", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Loại vòng tuyển dụng.
        /// </summary>
        public static string RecruitmentType {
            get {
                return ResourceManager.GetString("RecruitmentType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Quan hệ.
        /// </summary>
        public static string Relationship {
            get {
                return ResourceManager.GetString("Relationship", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Quản lý mối quan hệ.
        /// </summary>
        public static string RelationshipManagement {
            get {
                return ResourceManager.GetString("RelationshipManagement", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Gia hạn thẻ BHYT.
        /// </summary>
        public static string RenewHICard {
            get {
                return ResourceManager.GetString("RenewHICard", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Vui lòng nhập thông tin &quot;{0}&quot;.
        /// </summary>
        public static string Required {
            get {
                return ResourceManager.GetString("Required", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ghi nhận kết quả.
        /// </summary>
        public static string ResultsRecord {
            get {
                return ResourceManager.GetString("ResultsRecord", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Khen thưởng - kỷ luật.
        /// </summary>
        public static string RewardDiscipline {
            get {
                return ResourceManager.GetString("RewardDiscipline", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Quản lý khen thưởng - kỷ luật.
        /// </summary>
        public static string RewardDisciplineManagement {
            get {
                return ResourceManager.GetString("RewardDisciplineManagement", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Quản lý thông tin nhóm người dùng.
        /// </summary>
        public static string RolesManagement {
            get {
                return ResourceManager.GetString("RolesManagement", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ngạch lương.
        /// </summary>
        public static string SalaryGrade {
            get {
                return ResourceManager.GetString("SalaryGrade", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Bậc lương.
        /// </summary>
        public static string SalaryRank {
            get {
                return ResourceManager.GetString("SalaryRank", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Thang bảng lương.
        /// </summary>
        public static string Scale {
            get {
                return ResourceManager.GetString("Scale", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Lịch làm việc.
        /// </summary>
        public static string Schedule {
            get {
                return ResourceManager.GetString("Schedule", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Thay đổi lịch làm việc.
        /// </summary>
        public static string ScheduleChange {
            get {
                return ResourceManager.GetString("ScheduleChange", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tìm kiếm.
        /// </summary>
        public static string Search {
            get {
                return ResourceManager.GetString("Search", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Dịch vụ.
        /// </summary>
        public static string SelfService {
            get {
                return ResourceManager.GetString("SelfService", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Thiết lập thông số.
        /// </summary>
        public static string SetupParameters {
            get {
                return ResourceManager.GetString("SetupParameters", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Quyết toán thôi việc.
        /// </summary>
        public static string SeveranceSettlement {
            get {
                return ResourceManager.GetString("SeveranceSettlement", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ca làm việc.
        /// </summary>
        public static string Shift {
            get {
                return ResourceManager.GetString("Shift", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Kỹ năng.
        /// </summary>
        public static string Skill {
            get {
                return ResourceManager.GetString("Skill", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ngày phép chuẩn.
        /// </summary>
        public static string StandardAnnualLeave {
            get {
                return ResourceManager.GetString("StandardAnnualLeave", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Hệ thống.
        /// </summary>
        public static string System {
            get {
                return ResourceManager.GetString("System", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Quản trị hệ thống.
        /// </summary>
        public static string SystemAdministration {
            get {
                return ResourceManager.GetString("SystemAdministration", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tham số hệ thống.
        /// </summary>
        public static string SystemParameter {
            get {
                return ResourceManager.GetString("SystemParameter", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Thôi việc.
        /// </summary>
        public static string Termination {
            get {
                return ResourceManager.GetString("Termination", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Danh sách thôi việc.
        /// </summary>
        public static string TerminationList {
            get {
                return ResourceManager.GetString("TerminationList", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Thiết lập tham số cơ bản.
        /// </summary>
        public static string TerminationParameter {
            get {
                return ResourceManager.GetString("TerminationParameter", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Lí do thôi việc.
        /// </summary>
        public static string TerminationReason {
            get {
                return ResourceManager.GetString("TerminationReason", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Loại thôi việc.
        /// </summary>
        public static string TerminationType {
            get {
                return ResourceManager.GetString("TerminationType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Chấm công.
        /// </summary>
        public static string Timekeeping {
            get {
                return ResourceManager.GetString("Timekeeping", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Thống kê đi trễ về sớm.
        /// </summary>
        public static string TimeKeepingReport {
            get {
                return ResourceManager.GetString("TimeKeepingReport", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Chấm công.
        /// </summary>
        public static string Timesheet {
            get {
                return ResourceManager.GetString("Timesheet", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Chu kỳ chấm công.
        /// </summary>
        public static string TimesheetCyclic {
            get {
                return ResourceManager.GetString("TimesheetCyclic", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Đào tạo.
        /// </summary>
        public static string Training {
            get {
                return ResourceManager.GetString("Training", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Chuyển ứng viên thành nhân viên.
        /// </summary>
        public static string TransferCandidate {
            get {
                return ResourceManager.GetString("TransferCandidate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cập nhật.
        /// </summary>
        public static string Update {
            get {
                return ResourceManager.GetString("Update", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Quản lý Tài khoản - Nhóm.
        /// </summary>
        public static string UserGroupManagement {
            get {
                return ResourceManager.GetString("UserGroupManagement", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Kinh nghiệm làm việc.
        /// </summary>
        public static string WorkingBackground {
            get {
                return ResourceManager.GetString("WorkingBackground", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Nguyện vọng làm việc.
        /// </summary>
        public static string WorkingExpectation {
            get {
                return ResourceManager.GetString("WorkingExpectation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Lịch sử làm việc.
        /// </summary>
        public static string WorkingHistory {
            get {
                return ResourceManager.GetString("WorkingHistory", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Quản lý lịch sử làm việc.
        /// </summary>
        public static string WorkingHistoryManagement {
            get {
                return ResourceManager.GetString("WorkingHistoryManagement", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Quá trình làm việc.
        /// </summary>
        public static string WorkingRecord {
            get {
                return ResourceManager.GetString("WorkingRecord", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Quản lý quá trình làm việc.
        /// </summary>
        public static string WorkingRecordManagement {
            get {
                return ResourceManager.GetString("WorkingRecordManagement", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Bảng phân công lịch làm việc.
        /// </summary>
        public static string WorkingSchedule {
            get {
                return ResourceManager.GetString("WorkingSchedule", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tổng hợp làm ngoài giờ.
        /// </summary>
        public static string YearlyOTReport {
            get {
                return ResourceManager.GetString("YearlyOTReport", resourceCulture);
            }
        }
    }
}
