//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Eagle.ShopCart.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class Customer
    {
        public int Customer_Id { get; set; }
        public int CustomerType_Id { get; set; }
        public System.Guid Customer_No { get; set; }
        public string Customer_MemberCardNo { get; set; }
        public string CustomerName { get; set; }
        public string ContactName { get; set; }
        public string IDCardNo { get; set; }
        public string PassPortNo { get; set; }
        public string TaxCode { get; set; }
        public Nullable<System.DateTime> BirthDay { get; set; }
        public string Address { get; set; }
        public string City { get; set; }
        public string Region { get; set; }
        public string Country { get; set; }
        public string PostalCode { get; set; }
        public string Phone { get; set; }
        public string Mobile { get; set; }
        public string Fax { get; set; }
        public string Email { get; set; }
        public string PasswordHash { get; set; }
        public string PasswordSalt { get; set; }
        public bool Verified { get; set; }
        public bool Discontinued { get; set; }
        public string IPLog { get; set; }
        public Nullable<System.DateTime> CreatedOnDate { get; set; }
        public Nullable<System.DateTime> LastModifiedOnDate { get; set; }
    }
}
