//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Eagle.ShopCart.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class Product_Coupons
    {
        public int VendorId { get; set; }
        public string CultureCode { get; set; }
        public int Coupon_Id { get; set; }
        public string Coupon_Code { get; set; }
        public byte Coupon_Type { get; set; }
        public string Coupon_Name { get; set; }
        public decimal Coupon_Amount { get; set; }
        public Nullable<byte> Coupon_IsPercent { get; set; }
        public string Coupon_Description { get; set; }
        public Nullable<System.DateTime> Coupon_StartDate { get; set; }
        public Nullable<System.DateTime> Coupon_EndDate { get; set; }
        public string Coupon_Status { get; set; }
        public Nullable<System.DateTime> CreatedOnDate { get; set; }
        public Nullable<System.DateTime> LastModifiedOnDate { get; set; }
    }
}
