//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Eagle.ShopCart.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class Product_AttributeOptions
    {
        public int Attribute_Id { get; set; }
        public int Option_Id { get; set; }
        public string Option_Name { get; set; }
        public Nullable<decimal> Option_Value { get; set; }
    }
}
