//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Eagle.ShopCart.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class Product_Types
    {
        public string Category_Code { get; set; }
        public int Product_TypeId { get; set; }
        public string Product_TypeName { get; set; }
        public string Product_TypeDescription { get; set; }
        public Nullable<int> Product_TypeSortKey { get; set; }
        public string Product_TypePublish { get; set; }
    }
}
