//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Eagle.ShopCart.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class Report_Types
    {
        public int ApplicationId { get; set; }
        public int TypeId { get; set; }
        public int ParentId { get; set; }
        public string CultureCode { get; set; }
        public string Name { get; set; }
        public string Description { get; set; }
        public int SortKey { get; set; }
        public int Depth { get; set; }
        public Nullable<System.DateTime> PostedDate { get; set; }
        public Nullable<System.DateTime> LastUpdatedDate { get; set; }
        public bool Status { get; set; }
    }
}
