//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Eagle.ShopCart.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class ShippingCarrier
    {
        public int ShippingCarrier_Id { get; set; }
        public string ShippingCarrier_Name { get; set; }
        public string Phone { get; set; }
        public Nullable<int> ListOrder { get; set; }
        public Nullable<bool> Discontinued { get; set; }
    }
}
