//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Eagle.ShopCart.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class ShippingRate
    {
        public int ShippingCarrier_Id { get; set; }
        public int ShippingMethod_Id { get; set; }
        public int ShippingRate_Id { get; set; }
        public int ShippingRate_CountryId { get; set; }
        public string ShippingRate_Name { get; set; }
        public string ShippingRate_ZipStart { get; set; }
        public string ShippingRate_ZipEnd { get; set; }
        public decimal ShippingRate_WeightStart { get; set; }
        public decimal ShippingRate_WeightEnd { get; set; }
        public decimal ShippingRate_Value { get; set; }
        public decimal ShippingRate_PackageFee { get; set; }
        public decimal ShippingRate_VAT { get; set; }
        public string ShippingRate_CurrencyCode { get; set; }
        public int ShippingRate_ListOrder { get; set; }
    }
}
