//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Eagle.ShopCart.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class ShippingCity
    {
        public int CityId { get; set; }
        public string CityName_Vi { get; set; }
        public string CityName_En { get; set; }
        public int CountryId { get; set; }
        public Nullable<int> Status { get; set; }
    }
}
