//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Eagle.ShopCart.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class Vendor_Temp
    {
        public Nullable<System.Guid> ApplicationCode { get; set; }
        public int VendorTempId { get; set; }
        public Nullable<int> CountryId { get; set; }
        public string Category_Code { get; set; }
        public string VendorName { get; set; }
        public string Address { get; set; }
        public string Telephone { get; set; }
        public string Email { get; set; }
        public string CurrencyCode { get; set; }
        public string StoreName { get; set; }
        public string StoreCompanyName { get; set; }
        public string Description { get; set; }
        public string Title { get; set; }
        public string FirstName { get; set; }
        public string MiddleName { get; set; }
        public string LastName { get; set; }
        public Nullable<System.DateTime> CreatedOnDate { get; set; }
        public bool Authorized { get; set; }
    }
}
