//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Eagle.ShopCart.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class Vendor_OrderPromotions
    {
        public int VendorOrderPromotionId { get; set; }
        public int VendorId { get; set; }
        public int PromotionId { get; set; }
        public Nullable<System.DateTime> StartDate { get; set; }
        public Nullable<System.DateTime> EndDate { get; set; }
        public Nullable<System.DateTime> CreatedOnDate { get; set; }
        public Nullable<System.DateTime> LastModifiedDate { get; set; }
        public Nullable<bool> Discontinued { get; set; }
    }
}
