//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Eagle.ShopCart.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class Vendor_Branches
    {
        public int Branch_ID { get; set; }
        public string Branch_Code { get; set; }
        public string Branch_Name { get; set; }
        public string Branch_Address { get; set; }
        public string Branch_Phone { get; set; }
        public string Branch_Fax { get; set; }
        public string Branch_Place { get; set; }
        public string Branch_TaxCode { get; set; }
        public string Branch_HotLine { get; set; }
        public string Branch_Status { get; set; }
    }
}
