//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Eagle.Core
{
    using System;
    using System.Collections.Generic;
    
    public partial class ContentItem
    {
        public Nullable<int> PageId { get; set; }
        public Nullable<int> ModuleId { get; set; }
        public int ContentTypeId { get; set; }
        public Nullable<int> ScopeTypeId { get; set; }
        public int ContentItemId { get; set; }
        public Nullable<int> ParentId { get; set; }
        public Nullable<int> Depth { get; set; }
        public string Lineage { get; set; }
        public Nullable<int> ListOrder { get; set; }
        public string ContentItemName { get; set; }
        public string ContentItemTitle { get; set; }
        public string ContentKey { get; set; }
        public string Content { get; set; }
        public Nullable<bool> IsParent { get; set; }
        public bool IsActive { get; set; }
    }
}
