//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Eagle.Core
{
    using System;
    using System.Collections.Generic;
    
    public partial class Country
    {
        public int CountryId { get; set; }
        public string CountryName { get; set; }
        public string ISO2_Alpha { get; set; }
        public string ISO3_Alpha { get; set; }
        public string IANA_Internet { get; set; }
        public string UN_Vehicle { get; set; }
        public string IOC_Olympic { get; set; }
        public string UN_ISO_Numeric { get; set; }
        public string ITU_Calling { get; set; }
        public string Status { get; set; }
    }
}
