//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Eagle.Core
{
    using System;
    using System.Collections.Generic;
    
    public partial class DOC_tblDocumentReference
    {
        public DOC_tblDocumentReference()
        {
            this.DOC_tblDocument = new HashSet<DOC_tblDocument>();
        }
    
        public int LSReferenceId { get; set; }
        public string Code { get; set; }
        public string Name { get; set; }
        public string VNName { get; set; }
        public Nullable<int> Rank { get; set; }
        public string Note { get; set; }
        public Nullable<bool> Used { get; set; }
    
        public virtual ICollection<DOC_tblDocument> DOC_tblDocument { get; set; }
    }
}
