//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Eagle.Core
{
    using System;
    using System.Collections.Generic;
    
    public partial class Gallery_Collections
    {
        public int TopicId { get; set; }
        public int CollectionId { get; set; }
        public string Title { get; set; }
        public string IconFile { get; set; }
        public Nullable<int> ListOrder { get; set; }
        public string Description { get; set; }
        public string Tags { get; set; }
        public string Url { get; set; }
        public Nullable<System.Guid> CreatedByUserId { get; set; }
        public Nullable<System.DateTime> CreatedOnDate { get; set; }
        public Nullable<System.Guid> LastModifiedByUserId { get; set; }
        public Nullable<System.DateTime> LastModifieddDate { get; set; }
        public string IPLog { get; set; }
        public string IPLastUpdate { get; set; }
        public string Status { get; set; }
    }
}
