//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Eagle.Core
{
    using System;
    using System.Collections.Generic;
    
    public partial class HR_tblReward
    {
        public int RewardID { get; set; }
        public int EmpID { get; set; }
        public int Type { get; set; }
        public int LSRewardID { get; set; }
        public int LSRewardLevelID { get; set; }
        public System.DateTime EffectiveDate { get; set; }
        public string Reason { get; set; }
        public Nullable<bool> Decision { get; set; }
        public string DecisionNo { get; set; }
        public Nullable<System.DateTime> SignedDate { get; set; }
        public Nullable<int> SignerEmpID { get; set; }
        public Nullable<int> FileId { get; set; }
        public string Note { get; set; }
    
        public virtual HR_tblEmp HR_tblEmp { get; set; }
        public virtual LS_tblReward LS_tblReward { get; set; }
        public virtual LS_tblRewardLevel LS_tblRewardLevel { get; set; }
    }
}
