//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Eagle.Core
{
    using System;
    using System.Collections.Generic;
    
    public partial class HR_tblWorkingHistory
    {
        public int WorkingHistoryID { get; set; }
        public int EmpID { get; set; }
        public Nullable<System.DateTime> FromDate { get; set; }
        public Nullable<System.DateTime> ToDate { get; set; }
        public string WorkFor { get; set; }
        public string Position { get; set; }
        public string Duty { get; set; }
        public string LeaveReason { get; set; }
        public string FormerCompanyAddress { get; set; }
        public string ContactPersonName { get; set; }
        public string ContactPersonPosition { get; set; }
        public string ContactPersonPhone { get; set; }
        public string ContactPersonEmail { get; set; }
        public string Note { get; set; }
    
        public virtual HR_tblEmp HR_tblEmp { get; set; }
    }
}
