//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Eagle.Core
{
    using System;
    using System.Collections.Generic;
    
    public partial class HR_tblEmp
    {
        public HR_tblEmp()
        {
            this.HR_tblProject = new HashSet<HR_tblProject>();
            this.HR_tblRelationship = new HashSet<HR_tblRelationship>();
            this.HR_tblReward = new HashSet<HR_tblReward>();
            this.HR_tblWorkingHistory = new HashSet<HR_tblWorkingHistory>();
            this.LS_tblOnlineProcessMailBcc = new HashSet<LS_tblOnlineProcessMailBcc>();
            this.LS_tblOnlineProcessMailCc = new HashSet<LS_tblOnlineProcessMailCc>();
            this.Mail_SendMailCalendar = new HashSet<Mail_SendMailCalendar>();
            this.PR_tblAdditionSalary = new HashSet<PR_tblAdditionSalary>();
            this.PR_tblDeductionSalary = new HashSet<PR_tblDeductionSalary>();
            this.PR_tblSalary = new HashSet<PR_tblSalary>();
            this.REC_tblDemand = new HashSet<REC_tblDemand>();
            this.REC_tblPlan = new HashSet<REC_tblPlan>();
            this.REC_tblPlanComment = new HashSet<REC_tblPlanComment>();
            this.REC_tblProjectTournament = new HashSet<REC_tblProjectTournament>();
            this.REC_tblDemandComment = new HashSet<REC_tblDemandComment>();
            this.SYS_tblOnlineProcessEmp = new HashSet<SYS_tblOnlineProcessEmp>();
            this.SYS_tblUserAccount = new HashSet<SYS_tblUserAccount>();
            this.TER_tblTermination = new HashSet<TER_tblTermination>();
            this.TimeSheet_tblAssignEmpSchedule = new HashSet<TimeSheet_tblAssignEmpSchedule>();
            this.Timesheet_tblLeaveApplicationMaster = new HashSet<Timesheet_tblLeaveApplicationMaster>();
            this.Timesheet_tblLeaveApplicationMaster1 = new HashSet<Timesheet_tblLeaveApplicationMaster>();
            this.Timesheet_tblLeaveApplicationMaster2 = new HashSet<Timesheet_tblLeaveApplicationMaster>();
            this.Timesheet_tblLeaveApplicationMaster3 = new HashSet<Timesheet_tblLeaveApplicationMaster>();
            this.Timesheet_tblLeaveApplicationMaster4 = new HashSet<Timesheet_tblLeaveApplicationMaster>();
            this.Timesheet_tblLeaveApplicationMaster5 = new HashSet<Timesheet_tblLeaveApplicationMaster>();
            this.Timesheet_tblOTLimit = new HashSet<Timesheet_tblOTLimit>();
            this.Timesheet_tblOTLimitByStaff = new HashSet<Timesheet_tblOTLimitByStaff>();
            this.Timesheet_tblOTRecordMaster = new HashSet<Timesheet_tblOTRecordMaster>();
            this.Timesheet_tblReconciliation = new HashSet<Timesheet_tblReconciliation>();
            this.Timesheet_tblStandAnualLeaveDays = new HashSet<Timesheet_tblStandAnualLeaveDays>();
            this.TR_tblDurationUser = new HashSet<TR_tblDurationUser>();
            this.TR_tblPlan = new HashSet<TR_tblPlan>();
            this.TR_tblTrainingRequest = new HashSet<TR_tblTrainingRequest>();
        }
    
        public int EmpID { get; set; }
        public Nullable<System.Guid> EmpNo { get; set; }
        public string EmpCode { get; set; }
        public string FirstName { get; set; }
        public string LastName { get; set; }
        public int Gender { get; set; }
        public string BloodType { get; set; }
        public string Email { get; set; }
        public string Telephone { get; set; }
        public string Mobile { get; set; }
        public Nullable<int> FileId { get; set; }
        public string IDNo { get; set; }
        public Nullable<System.DateTime> IDIssuedDate { get; set; }
        public Nullable<int> IDIssuedPlace { get; set; }
        public string TaxNo { get; set; }
        public string PAddress { get; set; }
        public Nullable<int> PLSCountryID { get; set; }
        public Nullable<int> PLSProvinceID { get; set; }
        public Nullable<int> PLSDistrictID { get; set; }
        public string TAddress { get; set; }
        public Nullable<int> TLSCountryID { get; set; }
        public Nullable<int> TLSProvinceID { get; set; }
        public Nullable<int> TLSDistrictID { get; set; }
        public int LSCompanyID { get; set; }
        public Nullable<System.DateTime> DOB { get; set; }
        public Nullable<int> YOB { get; set; }
        public Nullable<System.DateTime> StartDate { get; set; }
        public Nullable<System.DateTime> JoinDate { get; set; }
        public Nullable<int> BornLSCountryID { get; set; }
        public Nullable<int> BornLSProvinceID { get; set; }
        public Nullable<int> BornLSDistrictID { get; set; }
        public Nullable<int> NativeCountryID { get; set; }
        public Nullable<int> NativeProvinceID { get; set; }
        public Nullable<int> NativeDistrictID { get; set; }
        public Nullable<int> LSMaritalID { get; set; }
        public Nullable<int> LSNationalityID { get; set; }
        public Nullable<int> LSEthnicID { get; set; }
        public Nullable<int> LSReligionID { get; set; }
        public Nullable<int> LSEducationID { get; set; }
        public Nullable<int> LSMajorID { get; set; }
        public Nullable<int> LineManagerID { get; set; }
        public Nullable<int> LSLocationID { get; set; }
        public Nullable<int> LSPositionID { get; set; }
        public Nullable<int> CareerStatus { get; set; }
        public string AccountNumber { get; set; }
        public string AccountName { get; set; }
        public Nullable<int> LSBankID { get; set; }
        public Nullable<int> LSBankBranchID { get; set; }
        public Nullable<bool> PayByBank { get; set; }
        public Nullable<bool> SelfDeduction { get; set; }
        public Nullable<bool> DependDeduction { get; set; }
        public Nullable<int> NoOfDependent { get; set; }
        public string SIBook { get; set; }
        public string HIBook { get; set; }
        public string EmergencyContact { get; set; }
        public string EmergencyAddess { get; set; }
        public string EmergencyPhone { get; set; }
        public string EmergencyMobile { get; set; }
        public string UserMachineID { get; set; }
        public Nullable<System.DateTime> LastModifiedOnDate { get; set; }
        public Nullable<System.DateTime> CreatedOnDate { get; set; }
        public bool SI { get; set; }
        public bool HI { get; set; }
        public bool UI { get; set; }
        public bool Active { get; set; }
    
        public virtual ICollection<HR_tblProject> HR_tblProject { get; set; }
        public virtual ICollection<HR_tblRelationship> HR_tblRelationship { get; set; }
        public virtual ICollection<HR_tblReward> HR_tblReward { get; set; }
        public virtual ICollection<HR_tblWorkingHistory> HR_tblWorkingHistory { get; set; }
        public virtual ICollection<LS_tblOnlineProcessMailBcc> LS_tblOnlineProcessMailBcc { get; set; }
        public virtual ICollection<LS_tblOnlineProcessMailCc> LS_tblOnlineProcessMailCc { get; set; }
        public virtual ICollection<Mail_SendMailCalendar> Mail_SendMailCalendar { get; set; }
        public virtual ICollection<PR_tblAdditionSalary> PR_tblAdditionSalary { get; set; }
        public virtual ICollection<PR_tblDeductionSalary> PR_tblDeductionSalary { get; set; }
        public virtual ICollection<PR_tblSalary> PR_tblSalary { get; set; }
        public virtual ICollection<REC_tblDemand> REC_tblDemand { get; set; }
        public virtual ICollection<REC_tblPlan> REC_tblPlan { get; set; }
        public virtual ICollection<REC_tblPlanComment> REC_tblPlanComment { get; set; }
        public virtual ICollection<REC_tblProjectTournament> REC_tblProjectTournament { get; set; }
        public virtual ICollection<REC_tblDemandComment> REC_tblDemandComment { get; set; }
        public virtual ICollection<SYS_tblOnlineProcessEmp> SYS_tblOnlineProcessEmp { get; set; }
        public virtual ICollection<SYS_tblUserAccount> SYS_tblUserAccount { get; set; }
        public virtual ICollection<TER_tblTermination> TER_tblTermination { get; set; }
        public virtual ICollection<TimeSheet_tblAssignEmpSchedule> TimeSheet_tblAssignEmpSchedule { get; set; }
        public virtual ICollection<Timesheet_tblLeaveApplicationMaster> Timesheet_tblLeaveApplicationMaster { get; set; }
        public virtual ICollection<Timesheet_tblLeaveApplicationMaster> Timesheet_tblLeaveApplicationMaster1 { get; set; }
        public virtual ICollection<Timesheet_tblLeaveApplicationMaster> Timesheet_tblLeaveApplicationMaster2 { get; set; }
        public virtual ICollection<Timesheet_tblLeaveApplicationMaster> Timesheet_tblLeaveApplicationMaster3 { get; set; }
        public virtual ICollection<Timesheet_tblLeaveApplicationMaster> Timesheet_tblLeaveApplicationMaster4 { get; set; }
        public virtual ICollection<Timesheet_tblLeaveApplicationMaster> Timesheet_tblLeaveApplicationMaster5 { get; set; }
        public virtual ICollection<Timesheet_tblOTLimit> Timesheet_tblOTLimit { get; set; }
        public virtual ICollection<Timesheet_tblOTLimitByStaff> Timesheet_tblOTLimitByStaff { get; set; }
        public virtual ICollection<Timesheet_tblOTRecordMaster> Timesheet_tblOTRecordMaster { get; set; }
        public virtual ICollection<Timesheet_tblReconciliation> Timesheet_tblReconciliation { get; set; }
        public virtual ICollection<Timesheet_tblStandAnualLeaveDays> Timesheet_tblStandAnualLeaveDays { get; set; }
        public virtual ICollection<TR_tblDurationUser> TR_tblDurationUser { get; set; }
        public virtual ICollection<TR_tblPlan> TR_tblPlan { get; set; }
        public virtual ICollection<TR_tblTrainingRequest> TR_tblTrainingRequest { get; set; }
    }
}
