//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Eagle.Core
{
    using System;
    using System.Collections.Generic;
    
    public partial class LS_tblOnlineProcess
    {
        public LS_tblOnlineProcess()
        {
            this.LS_tblOnlineProcessMailBcc = new HashSet<LS_tblOnlineProcessMailBcc>();
            this.LS_tblOnlineProcessMailCc = new HashSet<LS_tblOnlineProcessMailCc>();
            this.SYS_tblProcessOnlineMaster = new HashSet<SYS_tblProcessOnlineMaster>();
        }
    
        public int DMQuiTrinhID { get; set; }
        public string NameProcessOnline { get; set; }
        public int FunctionID { get; set; }
        public int NoOfLevel { get; set; }
        public int IsStart { get; set; }
        public string Description { get; set; }
    
        public virtual ICollection<LS_tblOnlineProcessMailBcc> LS_tblOnlineProcessMailBcc { get; set; }
        public virtual ICollection<LS_tblOnlineProcessMailCc> LS_tblOnlineProcessMailCc { get; set; }
        public virtual ICollection<SYS_tblProcessOnlineMaster> SYS_tblProcessOnlineMaster { get; set; }
    }
}
