//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Eagle.Core
{
    using System;
    using System.Collections.Generic;
    
    public partial class LS_tblTrainingAnswerType
    {
        public int LSTrainingAnswerTypeID { get; set; }
        public string LSTrainingAnswerTypeCode { get; set; }
        public string Name { get; set; }
        public Nullable<int> LSTrainingApprisalItemID { get; set; }
        public Nullable<int> Rank { get; set; }
        public Nullable<bool> Used { get; set; }
        public string Note { get; set; }
    
        public virtual LS_tblTrainingApprisalItem LS_tblTrainingApprisalItem { get; set; }
    }
}
