//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Eagle.Core
{
    using System;
    using System.Collections.Generic;
    
    public partial class LS_tblTerminationReason
    {
        public LS_tblTerminationReason()
        {
            this.TER_tblTermination = new HashSet<TER_tblTermination>();
        }
    
        public int LSTerminationReasonID { get; set; }
        public string Code { get; set; }
        public string Name { get; set; }
        public string VNName { get; set; }
        public int Rank { get; set; }
        public bool Used { get; set; }
        public string Note { get; set; }
    
        public virtual ICollection<TER_tblTermination> TER_tblTermination { get; set; }
    }
}
