//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Eagle.Core
{
    using System;
    using System.Collections.Generic;
    
    public partial class LS_tblRewardLevel
    {
        public LS_tblRewardLevel()
        {
            this.HR_tblReward = new HashSet<HR_tblReward>();
        }
    
        public int LSRewardLevelID { get; set; }
        public string LSRewardLevelCode { get; set; }
        public string Name { get; set; }
        public string VNName { get; set; }
        public bool Used { get; set; }
        public Nullable<int> Rank { get; set; }
        public string Note { get; set; }
        public int Type { get; set; }
    
        public virtual ICollection<HR_tblReward> HR_tblReward { get; set; }
    }
}
