//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Eagle.Core
{
    using System;
    using System.Collections.Generic;
    
    public partial class LS_tblAnswerType
    {
        public LS_tblAnswerType()
        {
            this.LS_tblTrainingApprisalItem = new HashSet<LS_tblTrainingApprisalItem>();
        }
    
        public int LSAnswerTypeID { get; set; }
        public string AnswerTypeCode { get; set; }
        public string Name { get; set; }
        public Nullable<int> Rank { get; set; }
        public Nullable<bool> Used { get; set; }
        public string Note { get; set; }
    
        public virtual ICollection<LS_tblTrainingApprisalItem> LS_tblTrainingApprisalItem { get; set; }
    }
}
