//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Eagle.Core
{
    using System;
    using System.Collections.Generic;
    
    public partial class LS_tblTrainingExpense
    {
        public LS_tblTrainingExpense()
        {
            this.TR_tblTrainingRequestCost = new HashSet<TR_tblTrainingRequestCost>();
        }
    
        public int LSTrainingExpenseID { get; set; }
        public string Code { get; set; }
        public string Name { get; set; }
        public Nullable<int> Rank { get; set; }
        public bool Used { get; set; }
        public string Note { get; set; }
    
        public virtual ICollection<TR_tblTrainingRequestCost> TR_tblTrainingRequestCost { get; set; }
    }
}
