//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Eagle.Core
{
    using System;
    using System.Collections.Generic;
    
    public partial class LS_tblSalaryAdjust
    {
        public LS_tblSalaryAdjust()
        {
            this.PR_tblAdditionSalary = new HashSet<PR_tblAdditionSalary>();
            this.PR_tblAddSalaryByPosition = new HashSet<PR_tblAddSalaryByPosition>();
        }
    
        public int LSSalaryAdjustID { get; set; }
        public string LSSalaryAdjustCode { get; set; }
        public string Name { get; set; }
        public string VNName { get; set; }
        public int TypeAdd { get; set; }
        public bool PIT { get; set; }
        public bool AddSalary { get; set; }
        public int Type { get; set; }
        public short Rank { get; set; }
        public Nullable<decimal> MaxNonPIT { get; set; }
        public string Note { get; set; }
        public Nullable<bool> Used { get; set; }
    
        public virtual ICollection<PR_tblAdditionSalary> PR_tblAdditionSalary { get; set; }
        public virtual ICollection<PR_tblAddSalaryByPosition> PR_tblAddSalaryByPosition { get; set; }
    }
}
