//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Eagle.Core
{
    using System;
    using System.Collections.Generic;
    
    public partial class LS_tblProvince
    {
        public LS_tblProvince()
        {
            this.LS_tblBank = new HashSet<LS_tblBank>();
            this.LS_tblDistrict = new HashSet<LS_tblDistrict>();
            this.REC_tblCandidate = new HashSet<REC_tblCandidate>();
            this.REC_tblCandidate1 = new HashSet<REC_tblCandidate>();
            this.REC_tblCandidate2 = new HashSet<REC_tblCandidate>();
            this.REC_tblCandidate3 = new HashSet<REC_tblCandidate>();
            this.REC_tblCandidate4 = new HashSet<REC_tblCandidate>();
        }
    
        public int LSProvinceID { get; set; }
        public string LSProvinceCode { get; set; }
        public string Name { get; set; }
        public string VNName { get; set; }
        public Nullable<short> Rank { get; set; }
        public string Note { get; set; }
        public Nullable<bool> Used { get; set; }
        public Nullable<int> LSCountryID { get; set; }
    
        public virtual ICollection<LS_tblBank> LS_tblBank { get; set; }
        public virtual LS_tblCountry LS_tblCountry { get; set; }
        public virtual ICollection<LS_tblDistrict> LS_tblDistrict { get; set; }
        public virtual ICollection<REC_tblCandidate> REC_tblCandidate { get; set; }
        public virtual ICollection<REC_tblCandidate> REC_tblCandidate1 { get; set; }
        public virtual ICollection<REC_tblCandidate> REC_tblCandidate2 { get; set; }
        public virtual ICollection<REC_tblCandidate> REC_tblCandidate3 { get; set; }
        public virtual ICollection<REC_tblCandidate> REC_tblCandidate4 { get; set; }
    }
}
