//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Eagle.Core
{
    using System;
    using System.Collections.Generic;
    
    public partial class LS_tblTrainingLocation
    {
        public LS_tblTrainingLocation()
        {
            this.TR_tblPlan = new HashSet<TR_tblPlan>();
            this.TR_tblTrainingRequest = new HashSet<TR_tblTrainingRequest>();
        }
    
        public int LSTrainingLocationID { get; set; }
        public string Code { get; set; }
        public string Name { get; set; }
        public Nullable<int> Rank { get; set; }
        public bool Used { get; set; }
        public string Note { get; set; }
    
        public virtual ICollection<TR_tblPlan> TR_tblPlan { get; set; }
        public virtual ICollection<TR_tblTrainingRequest> TR_tblTrainingRequest { get; set; }
    }
}
