//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Eagle.Core
{
    using System;
    using System.Collections.Generic;
    
    public partial class LS_tblRecruitmentSource
    {
        public LS_tblRecruitmentSource()
        {
            this.REC_tblDemand = new HashSet<REC_tblDemand>();
            this.REC_tblPlan = new HashSet<REC_tblPlan>();
            this.REC_tblProject = new HashSet<REC_tblProject>();
        }
    
        public int LSRecruitmentSourceID { get; set; }
        public string LSRecruitmentSourceCode { get; set; }
        public string Name { get; set; }
        public Nullable<short> Rank { get; set; }
        public string Note { get; set; }
        public Nullable<bool> Used { get; set; }
    
        public virtual ICollection<REC_tblDemand> REC_tblDemand { get; set; }
        public virtual ICollection<REC_tblPlan> REC_tblPlan { get; set; }
        public virtual ICollection<REC_tblProject> REC_tblProject { get; set; }
    }
}
