//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Eagle.Core
{
    using System;
    using System.Collections.Generic;
    
    public partial class LS_tblSchool
    {
        public LS_tblSchool()
        {
            this.HR_tblQualification = new HashSet<HR_tblQualification>();
            this.REC_tblQualification = new HashSet<REC_tblQualification>();
        }
    
        public int LSSchoolID { get; set; }
        public string LSSchoolCode { get; set; }
        public string Name { get; set; }
        public string VNName { get; set; }
        public Nullable<short> Rank { get; set; }
        public string Note { get; set; }
        public Nullable<bool> Used { get; set; }
    
        public virtual ICollection<HR_tblQualification> HR_tblQualification { get; set; }
        public virtual ICollection<REC_tblQualification> REC_tblQualification { get; set; }
    }
}
