//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Eagle.Core
{
    using System;
    using System.Collections.Generic;
    
    public partial class LS_tblSalaryDeduction
    {
        public LS_tblSalaryDeduction()
        {
            this.PR_tblDeductionSalary = new HashSet<PR_tblDeductionSalary>();
        }
    
        public int LSDeductSalaryID { get; set; }
        public string LSDeductSalaryCode { get; set; }
        public string Name { get; set; }
        public string VNName { get; set; }
        public bool BeforeTax { get; set; }
        public Nullable<int> Rank { get; set; }
        public bool Used { get; set; }
        public string Note { get; set; }
    
        public virtual ICollection<PR_tblDeductionSalary> PR_tblDeductionSalary { get; set; }
    }
}
