//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Eagle.Core
{
    using System;
    using System.Collections.Generic;
    
    public partial class LS_tblLocation
    {
        public LS_tblLocation()
        {
            this.REC_tblWorkingExpectation = new HashSet<REC_tblWorkingExpectation>();
        }
    
        public int LSLocationID { get; set; }
        public string LSLocationCode { get; set; }
        public string Name { get; set; }
        public string VNName { get; set; }
        public Nullable<int> Rank { get; set; }
        public Nullable<bool> Used { get; set; }
        public string Note { get; set; }
    
        public virtual ICollection<REC_tblWorkingExpectation> REC_tblWorkingExpectation { get; set; }
    }
}
