//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Eagle.Core
{
    using System;
    using System.Collections.Generic;
    
    public partial class LS_tblTrainingApprisalItem
    {
        public LS_tblTrainingApprisalItem()
        {
            this.LS_tblTrainingAnswerType = new HashSet<LS_tblTrainingAnswerType>();
            this.TR_tblTemplateItem = new HashSet<TR_tblTemplateItem>();
            this.TR_tblTrainingEvaluationDetail = new HashSet<TR_tblTrainingEvaluationDetail>();
        }
    
        public int LSTrainingApprisalItemID { get; set; }
        public string LSTrainingApprisalItemCode { get; set; }
        public string Name { get; set; }
        public Nullable<int> LSTrainingApprisalPartID { get; set; }
        public Nullable<bool> IsMultiAnswer { get; set; }
        public Nullable<int> LSAnswerTypeID { get; set; }
        public Nullable<int> Rank { get; set; }
        public Nullable<bool> Used { get; set; }
        public string Note { get; set; }
    
        public virtual LS_tblAnswerType LS_tblAnswerType { get; set; }
        public virtual ICollection<LS_tblTrainingAnswerType> LS_tblTrainingAnswerType { get; set; }
        public virtual LS_tblTrainingApprisalPart LS_tblTrainingApprisalPart { get; set; }
        public virtual ICollection<TR_tblTemplateItem> TR_tblTemplateItem { get; set; }
        public virtual ICollection<TR_tblTrainingEvaluationDetail> TR_tblTrainingEvaluationDetail { get; set; }
    }
}
