//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Eagle.Core
{
    using System;
    using System.Collections.Generic;
    
    public partial class LS_tblCompanyDefine
    {
        public LS_tblCompanyDefine()
        {
            this.LS_tblCompany = new HashSet<LS_tblCompany>();
        }
    
        public int LSCompanyDefineID { get; set; }
        public string Name { get; set; }
        public string VNName { get; set; }
        public Nullable<int> Parent { get; set; }
    
        public virtual ICollection<LS_tblCompany> LS_tblCompany { get; set; }
    }
}
