//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Eagle.Core
{
    using System;
    using System.Collections.Generic;
    
    public partial class LS_tblCountry
    {
        public LS_tblCountry()
        {
            this.HR_tblQualification = new HashSet<HR_tblQualification>();
            this.LS_tblProvince = new HashSet<LS_tblProvince>();
            this.REC_tblCandidate = new HashSet<REC_tblCandidate>();
            this.REC_tblCandidate1 = new HashSet<REC_tblCandidate>();
            this.REC_tblCandidate2 = new HashSet<REC_tblCandidate>();
            this.REC_tblCandidate3 = new HashSet<REC_tblCandidate>();
            this.REC_tblQualification = new HashSet<REC_tblQualification>();
        }
    
        public int LSCountryID { get; set; }
        public string LSCountryCode { get; set; }
        public string Name { get; set; }
        public string VNName { get; set; }
        public Nullable<short> Rank { get; set; }
        public string Note { get; set; }
        public Nullable<bool> Used { get; set; }
    
        public virtual ICollection<HR_tblQualification> HR_tblQualification { get; set; }
        public virtual ICollection<LS_tblProvince> LS_tblProvince { get; set; }
        public virtual ICollection<REC_tblCandidate> REC_tblCandidate { get; set; }
        public virtual ICollection<REC_tblCandidate> REC_tblCandidate1 { get; set; }
        public virtual ICollection<REC_tblCandidate> REC_tblCandidate2 { get; set; }
        public virtual ICollection<REC_tblCandidate> REC_tblCandidate3 { get; set; }
        public virtual ICollection<REC_tblQualification> REC_tblQualification { get; set; }
    }
}
