//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Eagle.Core
{
    using System;
    using System.Collections.Generic;
    
    public partial class Mail_Accounts
    {
        public int Mail_Account_Id { get; set; }
        public int Mail_Server_Provider_Id { get; set; }
        public string Mail_Sender_Name { get; set; }
        public string Mail_Contact_Name { get; set; }
        public string Mail_Address { get; set; }
        public string Mail_Account { get; set; }
        public string Mail_Password { get; set; }
        public string Mail_Signature { get; set; }
    }
}
