//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Eagle.Core
{
    using System;
    using System.Collections.Generic;
    
    public partial class Mail_Templates
    {
        public int Mail_Template_Id { get; set; }
        public string Mail_Template_Name { get; set; }
        public string Mail_Template_Content { get; set; }
        public Nullable<bool> Mail_Template_Discontinued { get; set; }
        public Nullable<int> Mail_Type_Id { get; set; }
    }
}
