//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Eagle.Core
{
    using System;
    using System.Collections.Generic;
    
    public partial class Media_Composers
    {
        public int ComposerId { get; set; }
        public string ComposerName { get; set; }
        public string Alias { get; set; }
        public string FrontImage { get; set; }
        public string MainImage { get; set; }
        public string Description { get; set; }
        public Nullable<int> ListOrder { get; set; }
        public string IPLog { get; set; }
        public string IPModifiedLog { get; set; }
        public Nullable<System.DateTime> CreatedOnDate { get; set; }
        public Nullable<System.DateTime> LastModifiedOnDate { get; set; }
        public Nullable<System.Guid> CreatedByUserId { get; set; }
        public Nullable<System.Guid> LastModifiedByUserId { get; set; }
        public string Status { get; set; }
    }
}
