//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Eagle.Core
{
    using System;
    using System.Collections.Generic;
    
    public partial class Media_Types
    {
        public int TypeId { get; set; }
        public string TypeName { get; set; }
        public string TypeExt { get; set; }
        public string TypePath { get; set; }
        public Nullable<int> ListOrder { get; set; }
        public string Description { get; set; }
        public string Status { get; set; }
        public Nullable<System.DateTime> CreatedOnDate { get; set; }
        public Nullable<System.DateTime> ModifiedDate { get; set; }
        public string IPLog { get; set; }
        public string IPModifiedLog { get; set; }
        public Nullable<int> CreatedByUserId { get; set; }
        public Nullable<int> LastModifiedByUserId { get; set; }
    }
}
