//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Eagle.Core
{
    using System;
    using System.Collections.Generic;
    
    public partial class Media_Files
    {
        public int FileId { get; set; }
        public string FileName { get; set; }
        public string FileUrl { get; set; }
        public string Title { get; set; }
        public string Alias { get; set; }
        public string Lyric { get; set; }
        public Nullable<bool> AutoStart { get; set; }
        public Nullable<bool> MediaLoop { get; set; }
        public string Dimension { get; set; }
        public string Description { get; set; }
        public string Source { get; set; }
        public string Photo { get; set; }
        public string Thumbnail { get; set; }
        public Nullable<int> ClickThroughs { get; set; }
        public Nullable<int> SortKey { get; set; }
        public Nullable<int> UserId { get; set; }
        public string IPLog { get; set; }
        public Nullable<System.DateTime> PostedDate { get; set; }
        public string IPLastUpdate { get; set; }
        public Nullable<System.DateTime> LastUpdatedDate { get; set; }
        public string Status { get; set; }
    }
}
