//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Eagle.Core
{
    using System;
    using System.Collections.Generic;
    
    public partial class Media_FileRefs
    {
        public int FileRefId { get; set; }
        public Nullable<int> FileId { get; set; }
        public Nullable<int> AlbumId { get; set; }
        public Nullable<int> ArtistId { get; set; }
        public Nullable<int> ComposerId { get; set; }
        public Nullable<int> PlayListId { get; set; }
        public Nullable<int> TopicId { get; set; }
        public Nullable<int> TypeId { get; set; }
        public Nullable<int> VendorId { get; set; }
    }
}
