//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Eagle.Core
{
    using System;
    using System.Collections.Generic;
    
    public partial class Menu
    {
        public Nullable<int> PageId { get; set; }
        public int MenuTypeId { get; set; }
        public int MenuId { get; set; }
        public System.Guid MenuCode { get; set; }
        public Nullable<int> ParentId { get; set; }
        public int Depth { get; set; }
        public string Lineage { get; set; }
        public int ListOrder { get; set; }
        public Nullable<bool> HasChild { get; set; }
        public string MenuName { get; set; }
        public string MenuTitle { get; set; }
        public string MenuAlias { get; set; }
        public int ScopeTypeId { get; set; }
        public string Description { get; set; }
        public string Target { get; set; }
        public Nullable<int> IconFile { get; set; }
        public string IconClass { get; set; }
        public string Color { get; set; }
        public string CssClass { get; set; }
        public int MenuStatus { get; set; }
        public Nullable<System.DateTime> CreatedOnDate { get; set; }
        public Nullable<System.DateTime> LastModifiedOnDate { get; set; }
        public Nullable<int> CreatedByUserId { get; set; }
        public Nullable<int> LastModifiedByUserId { get; set; }
    }
}
