//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Eagle.Core
{
    using System;
    using System.Collections.Generic;
    
    public partial class MenuType
    {
        public int ApplicationId { get; set; }
        public int ScopeTypeId { get; set; }
        public string LanguageCode { get; set; }
        public int MenuTypeId { get; set; }
        public System.Guid MenuTypeCode { get; set; }
        public string MenuTypeName { get; set; }
        public string Description { get; set; }
        public int ListOrder { get; set; }
        public bool IsAdmin { get; set; }
        public bool MenuTypeStatus { get; set; }
        public Nullable<System.DateTime> PostedDate { get; set; }
        public Nullable<System.DateTime> LastUpdatedDate { get; set; }
    }
}
