//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Eagle.Core
{
    using System;
    using System.Collections.Generic;
    
    public partial class MenuRoute
    {
        public int ApplicationId { get; set; }
        public Nullable<int> ContentItemId { get; set; }
        public Nullable<int> PageId { get; set; }
        public string LanguageCode { get; set; }
        public int RouteId { get; set; }
        public string RouteName { get; set; }
        public string RouteUrl { get; set; }
        public string PhysicalFile { get; set; }
        public bool CheckPhysicalUrlAccess { get; set; }
        public string RouteValueDictionary { get; set; }
        public string Description { get; set; }
        public int ListOrder { get; set; }
        public bool Discontinued { get; set; }
    }
}
