//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Eagle.Core
{
    using System;
    using System.Collections.Generic;
    
    public partial class ModuleControl
    {
        public int ModuleControlId { get; set; }
        public int ModuleId { get; set; }
        public string ControlTitle { get; set; }
        public string ControlKey { get; set; }
        public string ControlSrc { get; set; }
        public int ControlType { get; set; }
        public string IconFile { get; set; }
        public int ViewOrder { get; set; }
    }
}
