//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Eagle.Core
{
    using System;
    using System.Collections.Generic;
    
    public partial class Order_Product_Options
    {
        public System.Guid Order_No { get; set; }
        public System.Guid Product_No { get; set; }
        public int Product_Option_Id { get; set; }
        public decimal Product_Option_Value { get; set; }
    }
}
