//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Eagle.Core
{
    using System;
    using System.Collections.Generic;
    
    public partial class PageOption
    {
        public int PageId { get; set; }
        public int OptionId { get; set; }
        public System.Guid OptionCode { get; set; }
        public string OptionName { get; set; }
        public string OptionValue { get; set; }
    }
}
