//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Eagle.Core
{
    using System;
    using System.Collections.Generic;
    
    public partial class PageBanner
    {
        public int BannerPageId { get; set; }
        public Nullable<int> BannerId { get; set; }
        public Nullable<int> PageId { get; set; }
    }
}
