//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Eagle.Core
{
    using System;
    using System.Collections.Generic;
    
    public partial class PR_tblPayroll_201407
    {
        public int PRID { get; set; }
        public int EmpID { get; set; }
        public int Year { get; set; }
        public int Month { get; set; }
        public decimal StandardWork { get; set; }
        public decimal ActualWork { get; set; }
        public Nullable<bool> isGross { get; set; }
        public Nullable<decimal> BasicSalaryNET { get; set; }
        public Nullable<decimal> BasicSalaryGROSS { get; set; }
        public Nullable<decimal> CoefSalary { get; set; }
        public Nullable<decimal> Salary { get; set; }
        public Nullable<decimal> BasicSalaryInsurance { get; set; }
        public Nullable<int> LSCurrencyIDSalary { get; set; }
        public Nullable<decimal> ExchangeRateSalary { get; set; }
        public Nullable<int> LSCurrencyIDInsurance { get; set; }
        public Nullable<decimal> ExchangeRateInsurance { get; set; }
        public decimal MinSalary { get; set; }
        public Nullable<decimal> CoefInS { get; set; }
        public decimal CoefInH { get; set; }
        public Nullable<decimal> CoefInE { get; set; }
        public Nullable<decimal> CoefInS_C { get; set; }
        public Nullable<decimal> CoefInH_C { get; set; }
        public Nullable<decimal> CoefInE_C { get; set; }
        public Nullable<decimal> InS { get; set; }
        public Nullable<decimal> InH { get; set; }
        public Nullable<decimal> InE { get; set; }
        public Nullable<decimal> InS_C { get; set; }
        public Nullable<decimal> InH_C { get; set; }
        public Nullable<decimal> InE_C { get; set; }
        public Nullable<int> Dependent { get; set; }
        public Nullable<decimal> DependentDeduction { get; set; }
        public Nullable<decimal> SelfDeduction { get; set; }
        public Nullable<decimal> Deduction { get; set; }
        public Nullable<decimal> DeductionBeforTax { get; set; }
        public Nullable<decimal> DeductionAfterTax { get; set; }
        public Nullable<decimal> AdditionSalaryBeforTax { get; set; }
        public Nullable<decimal> AdditionSalaryAfterTax { get; set; }
        public Nullable<decimal> OT { get; set; }
        public Nullable<decimal> OT_NoneTax { get; set; }
        public Nullable<decimal> OT_IncomeTax { get; set; }
        public Nullable<decimal> TotalIncome { get; set; }
        public Nullable<decimal> TaxableIncome { get; set; }
        public Nullable<decimal> IncomeTax { get; set; }
        public Nullable<decimal> TotalIncomeNET { get; set; }
        public Nullable<decimal> NetTakeHome { get; set; }
    }
}
