//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Eagle.Core
{
    using System;
    using System.Collections.Generic;
    
    public partial class PR_tblAdditionSalary
    {
        public int SalaryAdjustID { get; set; }
        public int EmpID { get; set; }
        public int LSSalaryAdjustID { get; set; }
        public string FromMonth { get; set; }
        public string ToMonth { get; set; }
        public string PaymentMethod { get; set; }
        public decimal Amount { get; set; }
        public Nullable<int> LSCurrencyID { get; set; }
        public bool isGross { get; set; }
        public string Note { get; set; }
    
        public virtual HR_tblEmp HR_tblEmp { get; set; }
        public virtual LS_tblCurrency LS_tblCurrency { get; set; }
        public virtual LS_tblSalaryAdjust LS_tblSalaryAdjust { get; set; }
    }
}
