//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Eagle.Core
{
    using System;
    using System.Collections.Generic;
    
    public partial class PR_tblSalary
    {
        public int SalaryID { get; set; }
        public int EmpID { get; set; }
        public System.DateTime EffectiveDate { get; set; }
        public string DecisionNo { get; set; }
        public Nullable<System.DateTime> SignDate { get; set; }
        public Nullable<int> EmpID_Signer { get; set; }
        public Nullable<int> FileID { get; set; }
        public Nullable<decimal> BasicSalary { get; set; }
        public Nullable<decimal> PercentBasicSalary { get; set; }
        public decimal ActualSalary { get; set; }
        public Nullable<int> LSCurrencyID { get; set; }
        public bool isGross { get; set; }
        public int TypeSalary { get; set; }
        public Nullable<int> SalaryScaleID { get; set; }
        public Nullable<int> SalaryGradeID { get; set; }
        public Nullable<int> SalaryRankID { get; set; }
        public Nullable<decimal> BasicCoef { get; set; }
        public Nullable<decimal> PercentBasicCoef { get; set; }
        public Nullable<decimal> ActualCoef { get; set; }
        public string Note { get; set; }
        public Nullable<decimal> InsuranceSalary { get; set; }
        public Nullable<int> InsuranceLSCurrencyID { get; set; }
    
        public virtual HR_tblEmp HR_tblEmp { get; set; }
        public virtual LS_tblCurrency LS_tblCurrency { get; set; }
        public virtual LS_tblCurrency LS_tblCurrency1 { get; set; }
        public virtual PR_tblSalaryGrade PR_tblSalaryGrade { get; set; }
        public virtual PR_tblSalaryRank PR_tblSalaryRank { get; set; }
        public virtual PR_tblSalaryScale PR_tblSalaryScale { get; set; }
    }
}
