//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Eagle.Core
{
    using System;
    using System.Collections.Generic;
    
    public partial class PR_tblInsuranceExchangeRate
    {
        public int LSInsuranceExchangeRateID { get; set; }
        public System.DateTime EffectiveDate { get; set; }
        public Nullable<int> LSCurrencyID { get; set; }
        public decimal ExchangeRate { get; set; }
        public string Note { get; set; }
    
        public virtual LS_tblCurrency LS_tblCurrency { get; set; }
    }
}
