//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Eagle.Core
{
    using System;
    using System.Collections.Generic;
    
    public partial class PR_tblSalary13Coef
    {
        public int SalaryCoefID { get; set; }
        public int Year { get; set; }
        public int EmpID { get; set; }
        public Nullable<int> CalMonth { get; set; }
        public Nullable<decimal> Coef { get; set; }
    }
}
