//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Eagle.Core
{
    using System;
    using System.Collections.Generic;
    
    public partial class PR_tblIncomeTaxGROSS
    {
        public int IncomeTaxGrossID { get; set; }
        public System.DateTime EffectiveDate { get; set; }
        public decimal IncomeTo1 { get; set; }
        public int Rate1 { get; set; }
        public decimal IncomeTo2 { get; set; }
        public int Rate2 { get; set; }
        public decimal IncomeTo3 { get; set; }
        public int Rate3 { get; set; }
        public decimal IncomeTo4 { get; set; }
        public int Rate4 { get; set; }
        public decimal IncomeTo5 { get; set; }
        public int Rate5 { get; set; }
        public decimal IncomeTo6 { get; set; }
        public int Rate6 { get; set; }
        public decimal IncomeTo7 { get; set; }
        public int Rate7 { get; set; }
    }
}
