//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Eagle.Core
{
    using System;
    using System.Collections.Generic;
    
    public partial class Product_TypeParameters
    {
        public int Product_TypeId { get; set; }
        public string Parameter_Name { get; set; }
        public string Parameter_Label { get; set; }
        public string Parameter_Description { get; set; }
        public Nullable<int> Parameter_ListOrder { get; set; }
        public string Parameter_Type { get; set; }
        public string Parameter_Values { get; set; }
        public string Parameter_Multiselect { get; set; }
        public string Parameter_Default { get; set; }
        public string Parameter_Unit { get; set; }
    }
}
