//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Eagle.Core
{
    using System;
    using System.Collections.Generic;
    
    public partial class REC_tblWorkingBackground
    {
        public int WokingbackgroupID { get; set; }
        public int CandidateID { get; set; }
        public Nullable<System.DateTime> FromMonth { get; set; }
        public Nullable<System.DateTime> ToMonth { get; set; }
        public string WorkFor { get; set; }
        public string Position { get; set; }
        public string Duty { get; set; }
        public string Address { get; set; }
        public string ContactName { get; set; }
        public string ContactPosition { get; set; }
        public string Phone { get; set; }
        public string Email { get; set; }
        public string ChangeReason { get; set; }
        public string Note { get; set; }
    
        public virtual REC_tblCandidate REC_tblCandidate { get; set; }
    }
}
