//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Eagle.Core
{
    using System;
    using System.Collections.Generic;
    
    public partial class REC_tblCandidateTournament_InterviewCriteria
    {
        public int CandidateTournamentID { get; set; }
        public int InterviewCriteriaID { get; set; }
        public string Note { get; set; }
        public Nullable<int> Rank { get; set; }
    
        public virtual REC_tblCandidateTournament REC_tblCandidateTournament { get; set; }
        public virtual REC_tblInterviewCriteria REC_tblInterviewCriteria { get; set; }
    }
}
