//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Eagle.Core
{
    using System;
    using System.Collections.Generic;
    
    public partial class REC_tblProject
    {
        public REC_tblProject()
        {
            this.REC_tblProjectFee = new HashSet<REC_tblProjectFee>();
            this.REC_tblProjectTournament = new HashSet<REC_tblProjectTournament>();
            this.LS_tblRecruitmentSource = new HashSet<LS_tblRecruitmentSource>();
            this.REC_tblCandidate = new HashSet<REC_tblCandidate>();
            this.REC_tblDemand = new HashSet<REC_tblDemand>();
        }
    
        public int ProjectID { get; set; }
        public string ProjectCode { get; set; }
        public System.DateTime ApplyDateFrom { get; set; }
        public System.DateTime ApplyDateTo { get; set; }
        public System.DateTime RecruitFrom { get; set; }
        public System.DateTime RecruitTo { get; set; }
        public int Status { get; set; }
        public Nullable<decimal> PlanCost { get; set; }
        public Nullable<decimal> ActualCost { get; set; }
        public Nullable<int> LSCurrencyID { get; set; }
        public Nullable<int> LSLocationID { get; set; }
        public string Content { get; set; }
        public string Description { get; set; }
    
        public virtual ICollection<REC_tblProjectFee> REC_tblProjectFee { get; set; }
        public virtual ICollection<REC_tblProjectTournament> REC_tblProjectTournament { get; set; }
        public virtual ICollection<LS_tblRecruitmentSource> LS_tblRecruitmentSource { get; set; }
        public virtual ICollection<REC_tblCandidate> REC_tblCandidate { get; set; }
        public virtual ICollection<REC_tblDemand> REC_tblDemand { get; set; }
    }
}
