//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Eagle.Core
{
    using System;
    using System.Collections.Generic;
    
    public partial class REC_tblCandidate
    {
        public REC_tblCandidate()
        {
            this.REC_tblCandidateTournament = new HashSet<REC_tblCandidateTournament>();
            this.REC_tblInterviewCalendar = new HashSet<REC_tblInterviewCalendar>();
            this.REC_tblQualification = new HashSet<REC_tblQualification>();
            this.REC_tblWorkingBackground = new HashSet<REC_tblWorkingBackground>();
            this.REC_tblWorkingExpectation = new HashSet<REC_tblWorkingExpectation>();
            this.DOC_tblDocument = new HashSet<DOC_tblDocument>();
            this.REC_tblProject = new HashSet<REC_tblProject>();
        }
    
        public int CandidateID { get; set; }
        public string CandidateCode { get; set; }
        public string FirstName { get; set; }
        public string LastName { get; set; }
        public Nullable<System.DateTime> DOB { get; set; }
        public Nullable<System.DateTime> ApplyDate { get; set; }
        public int Gender { get; set; }
        public Nullable<int> BornLSCountryID { get; set; }
        public Nullable<int> BornLSProvinceID { get; set; }
        public Nullable<int> BornLSDistrictID { get; set; }
        public Nullable<int> NativeCountryID { get; set; }
        public Nullable<int> NativeProvinceID { get; set; }
        public Nullable<int> NativeDistrictID { get; set; }
        public Nullable<int> PLSCountryID { get; set; }
        public Nullable<int> PLSProvinceID { get; set; }
        public Nullable<int> PLSDistrictID { get; set; }
        public string PAddress { get; set; }
        public Nullable<int> TLSCountryID { get; set; }
        public Nullable<int> TLSProvinceID { get; set; }
        public Nullable<int> TLSDistrictID { get; set; }
        public string TAddress { get; set; }
        public string Email { get; set; }
        public string Telephone { get; set; }
        public string Mobile { get; set; }
        public string IDNo { get; set; }
        public Nullable<System.DateTime> IDIssuedDate { get; set; }
        public Nullable<int> IDIssuedPlace { get; set; }
        public Nullable<int> LSCompanyID { get; set; }
        public Nullable<int> LSMaritalID { get; set; }
        public Nullable<int> LSNationalityID { get; set; }
        public Nullable<int> LSEthnicID { get; set; }
        public Nullable<int> LSReligionID { get; set; }
        public Nullable<int> LSEducationID { get; set; }
        public Nullable<int> LSQualificationID { get; set; }
        public Nullable<int> LSMajorID { get; set; }
        public string EmergencyContact { get; set; }
        public string EmergencyAddess { get; set; }
        public string EmergencyPhone { get; set; }
        public string EmergencyMobile { get; set; }
        public string Skill { get; set; }
        public string Favourite { get; set; }
        public Nullable<int> Result { get; set; }
        public Nullable<int> EmpId { get; set; }
        public Nullable<int> FileId { get; set; }
        public string FileIds { get; set; }
    
        public virtual ApplicationFile ApplicationFile { get; set; }
        public virtual LS_tblCompany LS_tblCompany { get; set; }
        public virtual LS_tblCountry LS_tblCountry { get; set; }
        public virtual LS_tblCountry LS_tblCountry1 { get; set; }
        public virtual LS_tblCountry LS_tblCountry2 { get; set; }
        public virtual LS_tblCountry LS_tblCountry3 { get; set; }
        public virtual LS_tblDistrict LS_tblDistrict { get; set; }
        public virtual LS_tblDistrict LS_tblDistrict1 { get; set; }
        public virtual LS_tblDistrict LS_tblDistrict2 { get; set; }
        public virtual LS_tblDistrict LS_tblDistrict3 { get; set; }
        public virtual LS_tblEducation LS_tblEducation { get; set; }
        public virtual LS_tblEthnic LS_tblEthnic { get; set; }
        public virtual LS_tblMajor LS_tblMajor { get; set; }
        public virtual LS_tblMarital LS_tblMarital { get; set; }
        public virtual LS_tblNationality LS_tblNationality { get; set; }
        public virtual LS_tblProvince LS_tblProvince { get; set; }
        public virtual LS_tblProvince LS_tblProvince1 { get; set; }
        public virtual LS_tblProvince LS_tblProvince2 { get; set; }
        public virtual LS_tblProvince LS_tblProvince3 { get; set; }
        public virtual LS_tblProvince LS_tblProvince4 { get; set; }
        public virtual LS_tblQualification LS_tblQualification { get; set; }
        public virtual LS_tblReligion LS_tblReligion { get; set; }
        public virtual ICollection<REC_tblCandidateTournament> REC_tblCandidateTournament { get; set; }
        public virtual ICollection<REC_tblInterviewCalendar> REC_tblInterviewCalendar { get; set; }
        public virtual ICollection<REC_tblQualification> REC_tblQualification { get; set; }
        public virtual ICollection<REC_tblWorkingBackground> REC_tblWorkingBackground { get; set; }
        public virtual ICollection<REC_tblWorkingExpectation> REC_tblWorkingExpectation { get; set; }
        public virtual ICollection<DOC_tblDocument> DOC_tblDocument { get; set; }
        public virtual ICollection<REC_tblProject> REC_tblProject { get; set; }
    }
}
