//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Eagle.Core
{
    using System;
    using System.Collections.Generic;
    
    public partial class REC_tblProjectTournament
    {
        public REC_tblProjectTournament()
        {
            this.REC_tblCandidateTournament = new HashSet<REC_tblCandidateTournament>();
            this.REC_tblInterviewCalendar = new HashSet<REC_tblInterviewCalendar>();
            this.REC_tblInterviewCriteria = new HashSet<REC_tblInterviewCriteria>();
        }
    
        public int ProjectTournamentID { get; set; }
        public int ProjectID { get; set; }
        public int LSRecruitmentTournamentID { get; set; }
        public int SEQ { get; set; }
        public System.DateTime FromDate { get; set; }
        public System.DateTime ToDate { get; set; }
        public int EmpID { get; set; }
    
        public virtual HR_tblEmp HR_tblEmp { get; set; }
        public virtual ICollection<REC_tblCandidateTournament> REC_tblCandidateTournament { get; set; }
        public virtual ICollection<REC_tblInterviewCalendar> REC_tblInterviewCalendar { get; set; }
        public virtual REC_tblProject REC_tblProject { get; set; }
        public virtual ICollection<REC_tblInterviewCriteria> REC_tblInterviewCriteria { get; set; }
    }
}
