//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Eagle.Core
{
    using System;
    using System.Collections.Generic;
    
    public partial class REC_tblInterviewCriteria
    {
        public REC_tblInterviewCriteria()
        {
            this.REC_tblCandidateTournament_InterviewCriteria = new HashSet<REC_tblCandidateTournament_InterviewCriteria>();
            this.REC_tblProjectTournament = new HashSet<REC_tblProjectTournament>();
        }
    
        public int InterviewCriteriaID { get; set; }
        public Nullable<int> InterviewCriteriaTypeID { get; set; }
        public string Code { get; set; }
        public string Name { get; set; }
        public Nullable<int> Rank { get; set; }
        public Nullable<bool> Used { get; set; }
        public string Note { get; set; }
    
        public virtual ICollection<REC_tblCandidateTournament_InterviewCriteria> REC_tblCandidateTournament_InterviewCriteria { get; set; }
        public virtual REC_tblInterviewCriteriaType REC_tblInterviewCriteriaType { get; set; }
        public virtual ICollection<REC_tblProjectTournament> REC_tblProjectTournament { get; set; }
    }
}
