//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Eagle.Core
{
    using System;
    using System.Collections.Generic;
    
    public partial class Report_Templates
    {
        public int Report_Template_Id { get; set; }
        public string Report_Template_Name { get; set; }
        public string Report_Template_Content { get; set; }
        public bool Report_Template_Discontinued { get; set; }
        public int Report_Type_Id { get; set; }
    }
}
