//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Eagle.Core
{
    using System;
    using System.Collections.Generic;
    
    public partial class ShippingDistrict
    {
        public int DistrictId { get; set; }
        public string District_Vi { get; set; }
        public string District_En { get; set; }
        public int CityId { get; set; }
        public Nullable<int> Status { get; set; }
    }
}
