//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Eagle.Core
{
    using System;
    using System.Collections.Generic;
    
    public partial class SI_tblPreviousRecord
    {
        public int PreviousRecordID { get; set; }
        public int EmpID { get; set; }
        public System.DateTime FromMonth { get; set; }
        public System.DateTime ToMonth { get; set; }
        public Nullable<decimal> NoOfMonth { get; set; }
        public string CompanyName { get; set; }
        public string Position { get; set; }
        public Nullable<decimal> Salary { get; set; }
        public string Note { get; set; }
    }
}
