//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Eagle.Core
{
    using System;
    using System.Collections.Generic;
    
    public partial class SI_tblInsuranceInformation
    {
        public int InsuranceID { get; set; }
        public int EmpID { get; set; }
        public string SIBook { get; set; }
        public Nullable<System.DateTime> StartDateSI { get; set; }
        public Nullable<System.DateTime> IssuedDateSIBook { get; set; }
        public System.DateTime JoinDateAtCompany { get; set; }
        public Nullable<int> LSProvinceIDIssuedSI { get; set; }
        public string HIBook { get; set; }
        public Nullable<int> LSHospitalIDOriginal { get; set; }
        public Nullable<System.DateTime> IssuedDateHIBook { get; set; }
        public Nullable<int> LSProvinceIDIssuedHI { get; set; }
        public Nullable<System.DateTime> StartDateHI { get; set; }
        public Nullable<int> LSHospitalIDNew { get; set; }
        public Nullable<System.DateTime> ReturnDateHI { get; set; }
        public string Note { get; set; }
    }
}
