//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Eagle.Core
{
    using System;
    using System.Collections.Generic;
    
    public partial class SkinPackageBackground
    {
        public int SkinBackgroundId { get; set; }
        public Nullable<int> SkinPackageId { get; set; }
        public string SkinBackground_Name { get; set; }
        public string SkinBackground_FileName { get; set; }
        public string SkinBackground_Url { get; set; }
        public Nullable<int> SkinBackground_SortKey { get; set; }
        public Nullable<bool> SkinBackground_Discontinued { get; set; }
    }
}
