//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Eagle.Core
{
    using System;
    using System.Collections.Generic;
    
    public partial class Skin
    {
        public int SkinId { get; set; }
        public Nullable<int> SkinTypeId { get; set; }
        public int SkinPackageId { get; set; }
        public Nullable<bool> IsSkinSelected { get; set; }
        public Nullable<bool> SkinStatus { get; set; }
    }
}
