//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Eagle.Core
{
    using System;
    using System.Collections.Generic;
    
    public partial class SYS_tblOnlineProcessEmp
    {
        public int OnlineProcessEmpID { get; set; }
        public int OnlineProcessID { get; set; }
        public int LSCompanyID { get; set; }
        public int EmpID { get; set; }
        public Nullable<bool> ApproveLevel1 { get; set; }
        public Nullable<bool> ApproveLevel2 { get; set; }
        public Nullable<bool> ApproveLevel3 { get; set; }
        public Nullable<bool> ApproveLevel4 { get; set; }
        public Nullable<bool> ApproveLevel5 { get; set; }
        public string Note { get; set; }
    
        public virtual HR_tblEmp HR_tblEmp { get; set; }
        public virtual LS_tblCompany LS_tblCompany { get; set; }
        public virtual SYS_tblProcessOnlineMaster SYS_tblProcessOnlineMaster { get; set; }
    }
}
