//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Eagle.Core
{
    using System;
    using System.Collections.Generic;
    
    public partial class TER_tblParameters
    {
        public int ID { get; set; }
        public int IsPaidForAnnualLeave { get; set; }
        public int IsPaidForMandatoryTrainingFee { get; set; }
        public int IsManipulatedLeaveDayRemains { get; set; }
        public int IsManipulatedForPaidLeave { get; set; }
        public int IsDeletedAfterTerminationSettlement { get; set; }
        public int IsAutomatedDecisionNo { get; set; }
        public int AutoNumberLenght { get; set; }
        public string Prefix { get; set; }
        public string Suffix { get; set; }
    }
}
