//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Eagle.Core
{
    using System;
    using System.Collections.Generic;
    
    public partial class Timesheet_tbLeaveDayType
    {
        public Timesheet_tbLeaveDayType()
        {
            this.SI_tblConvalescence = new HashSet<SI_tblConvalescence>();
            this.SI_tblInsuranceLeave = new HashSet<SI_tblInsuranceLeave>();
            this.Timesheet_tblLeaveApplicationMaster = new HashSet<Timesheet_tblLeaveApplicationMaster>();
        }
    
        public int LSLeaveDayTypeID { get; set; }
        public string LSLeaveDayTypeCode { get; set; }
        public int LSLeaveTypeID { get; set; }
        public string Name { get; set; }
        public Nullable<int> DaysPerYear { get; set; }
        public Nullable<int> DaysPerPeriod { get; set; }
        public Nullable<decimal> ConvalescenceLeave { get; set; }
        public Nullable<decimal> PercentSI { get; set; }
        public Nullable<bool> ExceptedHolidays { get; set; }
        public string Note { get; set; }
        public Nullable<bool> ForSI { get; set; }
    
        public virtual LS_tblLeaveType LS_tblLeaveType { get; set; }
        public virtual ICollection<SI_tblConvalescence> SI_tblConvalescence { get; set; }
        public virtual ICollection<SI_tblInsuranceLeave> SI_tblInsuranceLeave { get; set; }
        public virtual ICollection<Timesheet_tblLeaveApplicationMaster> Timesheet_tblLeaveApplicationMaster { get; set; }
    }
}
