//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Eagle.Core
{
    using System;
    using System.Collections.Generic;
    
    public partial class TimeSheet_tblAssignEmpSchedule
    {
        public int AssignEmpScheduleID { get; set; }
        public int EmpID { get; set; }
        public int Year { get; set; }
        public int ScheduleID { get; set; }
        public string Creater { get; set; }
        public Nullable<System.DateTime> CreateTime { get; set; }
        public string Editor { get; set; }
        public Nullable<System.DateTime> EditTime { get; set; }
    
        public virtual HR_tblEmp HR_tblEmp { get; set; }
        public virtual TimeSheet_tblSchedule TimeSheet_tblSchedule { get; set; }
    }
}
