//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Eagle.Core
{
    using System;
    using System.Collections.Generic;
    
    public partial class Timesheet_tblCyclic
    {
        public int CyclicID { get; set; }
        public int FromCyclic { get; set; }
        public int ToCyclic { get; set; }
        public string Note { get; set; }
    }
}
