//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Eagle.Core
{
    using System;
    using System.Collections.Generic;
    
    public partial class TR_tblTrainingEvaluation
    {
        public TR_tblTrainingEvaluation()
        {
            this.TR_tblTrainingEvaluationDetail = new HashSet<TR_tblTrainingEvaluationDetail>();
            this.TR_tblTrainingEvaluationPart = new HashSet<TR_tblTrainingEvaluationPart>();
        }
    
        public int TrainingEvaluationID { get; set; }
        public Nullable<int> TrainingRequestID { get; set; }
        public int EvaluationTemplateID { get; set; }
        public Nullable<int> EvaluationEmpID { get; set; }
        public string Comment { get; set; }
        public Nullable<int> Creater { get; set; }
        public Nullable<System.DateTime> CreateDate { get; set; }
        public Nullable<int> Updater { get; set; }
        public Nullable<System.DateTime> UpdateDate { get; set; }
        public Nullable<bool> IsComplete { get; set; }
    
        public virtual TR_tblTrainingRequest TR_tblTrainingRequest { get; set; }
        public virtual ICollection<TR_tblTrainingEvaluationDetail> TR_tblTrainingEvaluationDetail { get; set; }
        public virtual ICollection<TR_tblTrainingEvaluationPart> TR_tblTrainingEvaluationPart { get; set; }
    }
}
