//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Eagle.Core
{
    using System;
    using System.Collections.Generic;
    
    public partial class TR_tblTrainingRequestDuration
    {
        public TR_tblTrainingRequestDuration()
        {
            this.TR_tblDurationUser = new HashSet<TR_tblDurationUser>();
        }
    
        public int TrainingDurationID { get; set; }
        public int TrainingRequestID { get; set; }
        public Nullable<System.DateTime> FromDate { get; set; }
        public Nullable<System.DateTime> ToDate { get; set; }
        public int TotalDays { get; set; }
        public Nullable<int> TotalHours { get; set; }
    
        public virtual ICollection<TR_tblDurationUser> TR_tblDurationUser { get; set; }
        public virtual TR_tblTrainingRequest TR_tblTrainingRequest { get; set; }
    }
}
