//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Eagle.Core
{
    using System;
    using System.Collections.Generic;
    
    public partial class TR_tblTemplateItem
    {
        public int TemplateItemID { get; set; }
        public int EvaluationTemplateID { get; set; }
        public int LSTrainingApprisalPartID { get; set; }
        public int LSTrainingApprisalItemID { get; set; }
        public string Note { get; set; }
    
        public virtual LS_tblTrainingApprisalItem LS_tblTrainingApprisalItem { get; set; }
        public virtual TR_tblEvaluationTemplate TR_tblEvaluationTemplate { get; set; }
    }
}
