//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Eagle.Core
{
    using System;
    using System.Collections.Generic;
    
    public partial class TR_tblTrainingEvaluationDetail
    {
        public int TrainingEvaluationDetailID { get; set; }
        public int TrainingEvaluationID { get; set; }
        public Nullable<int> LSTrainingApprisalPartID { get; set; }
        public Nullable<int> LSTrainingApprisalItemID { get; set; }
        public Nullable<int> LSTrainingAnswerTypeID { get; set; }
        public Nullable<bool> IsAnswer { get; set; }
        public string Comment { get; set; }
    
        public virtual LS_tblTrainingApprisalItem LS_tblTrainingApprisalItem { get; set; }
        public virtual LS_tblTrainingApprisalPart LS_tblTrainingApprisalPart { get; set; }
        public virtual TR_tblTrainingEvaluation TR_tblTrainingEvaluation { get; set; }
    }
}
