//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Eagle.Core
{
    using System;
    using System.Collections.Generic;
    
    public partial class View_1
    {
        public Nullable<System.Guid> PageCode { get; set; }
        public Nullable<System.Guid> MenuTypeCode { get; set; }
        public int MenuId { get; set; }
        public System.Guid MenuCode { get; set; }
        public int ParentId { get; set; }
        public int Depth { get; set; }
        public int ListOrder { get; set; }
        public Nullable<bool> IsLeaf { get; set; }
        public string MenuName { get; set; }
        public string MenuTitle { get; set; }
        public string MenuAlias { get; set; }
        public string Description { get; set; }
        public string Target { get; set; }
        public Nullable<int> Icon { get; set; }
        public string CssClass { get; set; }
        public string Status { get; set; }
        public Nullable<System.Guid> ApplicationCode { get; set; }
        public int ScopeTypeId { get; set; }
        public string LanguageCode { get; set; }
        public string MenuTypeName { get; set; }
        public Nullable<System.Guid> SkinCode { get; set; }
        public string PageTitle { get; set; }
        public string PageUrl { get; set; }
        public string PagePath { get; set; }
        public string Keywords { get; set; }
    }
}
